
App:
  NameSpace:    seller-rating
  Name:         rating
  Service:      rating
  Environment:  local

API:
  Rest:
    Addr:         ":9000"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"
  Metrics:
    Addr:         ":9090"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"
  Probes:
    Addr:         ":9091"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"

Infra:
  TsDB:
    Conn:
      Host:             localhost
      Port:             5400
      User:             postgres
      DbName:           rating
      SchemaName:       rating
      MaxOpenConns:     30
      MaxIdleConns:     30
      MinConns:         5
      MaxConnLifetime:  "1h"
      Timeout:          "60s"
    Shards:
      0:
        MasterHost:     "localhost"
        MasterPort:     5400
        SlaveHost:      "localhost"
        SlavePort:      5400
        Password:       "postgres"

  Redis:
    Conn:
      Addrs:
        - "localhost:6379"
      Login:    ""
      Password: ""
      DBNum:    0
    Shards:
      0:
        MasterAddrs:    "localhost:6379"
        SlaveAddrs:     "localhost:6379"
        Password:       ""


